#version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:4.4
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  # indexer:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.indexer.yaml
  #   depends_on:
  #     - postgres
  #     - neo4j
  #   volumes:
  #     - .:/app
  #   command: python batch_indexer.py

volumes:
  postgres_data:
  neo4j_data: