openapi: 3.0.0
info:
  title: Sports Chatbot API
  description: >
    The Sports Chatbot API allows users to ask questions about indexed documents related to sports (e.g., soccer) using text or audio input. The API interacts with a PostgreSQL database and a Neo4j knowledge graph to generate responses using a GPT-based language model.
  version: 1.0.0
  contact:
    name: API Support
    url: https://example.com/contact
    email: support@example.com
servers:
  - url: http://localhost:8000
    description: Local Development Server

paths:
  /ask:
    post:
      summary: Ask a question about sports using text input
      description: >
        This endpoint accepts a text-based question about indexed sports-related documents and returns a generated answer using a large language model (LLM), PostgreSQL, and Neo4j.
      operationId: askQuestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionRequest'
      responses:
        '200':
          description: Answer generated by the LLM
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - basicAuth: []

  /ask_audio:
    post:
      summary: Ask a question about sports using audio input
      description: >
        This endpoint accepts an audio file with a spoken question about sports and returns a generated answer using a large language model (LLM), PostgreSQL, and Neo4j after transcribing the audio.
      operationId: askQuestionAudio
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Audio file containing the spoken question.
      responses:
        '200':
          description: Answer generated by the LLM after transcribing the audio
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - basicAuth: []

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    QuestionRequest:
      type: object
      properties:
        question:
          type: string
          description: The user's question.
      required:
        - question

    AnswerResponse:
      type: object
      properties:
        answer:
          type: string
          description: The answer generated by the language model, which combines information from PostgreSQL and Neo4j.

security:
  - basicAuth: []